import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Activity, Building2, Check, ExternalLink, Loader2, Plus, RefreshCw, ShieldCheck, Sparkles, UsersRound, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const sourceTypeLabels: Record<string, string> = { ministry: "교육부", curriculum_center: "교육과정정보센터", education_office: "교육청" };
const initialSource = { provider: "", title: "", sourceType: "education_office" as const, listingUrl: "", allowedUse: "link_only" as const };
// 개인 교사 파일럿에서는 역할 관리 UI를 숨기고, 기관 도입 준비가 끝난 뒤에만 재활성화합니다.
const ORGANIZATION_MANAGEMENT_ENABLED = false;

function ManagedAiUsagePanel({ usage, isLoading }: { usage?: any; isLoading: boolean }) {
  const summary = usage?.summary || { callCount: 0, successCount: 0, failureCount: 0, limitedCount: 0 };
  const operationLabel: Record<string, string> = { generation: "문항 생성", validation: "답·해설 검증", vision_extract: "자료 내용 추출" };
  const durationLabel: Record<string, string> = { under_5s: "5초 미만", "5_to_15s": "5~15초", "15_to_45s": "15~45초", over_45s: "45초 이상" };
  return <section className="mt-7 overflow-hidden rounded-2xl border border-[#B9DCCF] bg-white shadow-sm">
    <div className="border-b border-[#D6EBE2] bg-[#F7FCF9] px-5 py-4"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-[#15856B]" /><h2 className="font-bold text-[#183248]">개발용 관리형 AI 사용량</h2><Badge className="bg-[#E6F4EE] text-[#15856B] hover:bg-[#E6F4EE]">최근 {usage?.days || 14}일</Badge></div><p className="mt-1 text-xs leading-5 text-slate-500">사용자 ID·이메일·IP·프롬프트·문항·파일명은 기록하지 않고, 날짜·작업·결과·모델·처리 시간 구간의 합계만 표시합니다.</p></div>
    {isLoading ? <p className="p-5 text-sm text-slate-400">관리형 AI 사용량을 불러오는 중입니다.</p> : <><div className="grid gap-px bg-[#D6EBE2] sm:grid-cols-4"><div className="bg-white px-5 py-4"><p className="text-xs text-slate-500">호출 합계</p><p className="mt-1 text-2xl font-bold text-[#183248]">{summary.callCount}</p></div><div className="bg-white px-5 py-4"><p className="text-xs text-slate-500">성공</p><p className="mt-1 text-2xl font-bold text-[#15856B]">{summary.successCount}</p></div><div className="bg-white px-5 py-4"><p className="text-xs text-slate-500">실패</p><p className="mt-1 text-2xl font-bold text-[#B56716]">{summary.failureCount}</p></div><div className="bg-white px-5 py-4"><p className="text-xs text-slate-500">제한 응답</p><p className="mt-1 text-2xl font-bold text-[#7B56B3]">{summary.limitedCount}</p></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3 font-semibold">날짜</th><th className="px-5 py-3 font-semibold">작업</th><th className="px-5 py-3 font-semibold">결과</th><th className="px-5 py-3 font-semibold">모델</th><th className="px-5 py-3 font-semibold">처리 시간</th><th className="px-5 py-3 text-right font-semibold">호출</th></tr></thead><tbody className="divide-y divide-slate-100">{usage?.rows?.length ? usage.rows.map((row: any) => <tr key={row.id}><td className="px-5 py-3 text-slate-600">{row.usageDate}</td><td className="px-5 py-3 font-medium text-[#183248]">{operationLabel[row.operation] || row.operation}</td><td className="px-5 py-3"><Badge className={row.outcome === "success" ? "bg-[#E6F4EE] text-[#15856B] hover:bg-[#E6F4EE]" : row.outcome === "limited" ? "bg-[#F2EAFE] text-[#7B56B3] hover:bg-[#F2EAFE]" : "bg-[#FFF2D8] text-[#B56716] hover:bg-[#FFF2D8]"}>{row.outcome === "success" ? "성공" : row.outcome === "limited" ? "제한" : "실패"}</Badge></td><td className="px-5 py-3 font-mono text-xs text-slate-600">{row.model}</td><td className="px-5 py-3 text-xs text-slate-600">{durationLabel[row.durationBucket] || row.durationBucket}</td><td className="px-5 py-3 text-right font-semibold text-[#183248]">{row.callCount}</td></tr>) : <tr><td colSpan={6} className="px-5 py-9 text-center text-sm text-slate-400">아직 기록된 관리형 AI 호출이 없습니다. 관리형 AI로 문항을 생성하거나 이미지·스캔 자료를 등록하면 일별 합계가 표시됩니다.</td></tr>}</tbody></table></div>
      <p className="border-t border-slate-100 px-5 py-3 text-[11px] leading-5 text-slate-400">집계 보존 기준은 {usage?.retentionDays || 90}일입니다. 정식 공개 전에는 관리형 AI를 비활성화하거나 개인·로컬 AI 중심 정책으로 전환하세요.</p></>}
  </section>;
}

export default function Admin() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const { data: users, isLoading } = trpc.assessment.admin.users.useQuery(undefined, { enabled: user?.role === "admin" });
  const { data: sources, isLoading: sourcesLoading } = trpc.assessment.admin.officialSources.useQuery(undefined, { enabled: user?.role === "admin" });
  const { data: changes, isLoading: changesLoading } = trpc.assessment.admin.officialChanges.useQuery(undefined, { enabled: user?.role === "admin" });
  const { data: managedUsage, isLoading: managedUsageLoading } = trpc.assessment.admin.managedAiUsage.useQuery(undefined, { enabled: user?.role === "admin" });
  const [sourceForm, setSourceForm] = useState(initialSource);
  const setRole = trpc.assessment.admin.setRole.useMutation({ onSuccess: async () => { await utils.assessment.admin.users.invalidate(); toast.success("사용자 역할이 변경되었습니다."); }, onError: error => toast.error(error.message) });
  const setPlan = trpc.assessment.admin.setPlan.useMutation({ onSuccess: async () => { await utils.assessment.admin.users.invalidate(); toast.success("교사 플랜이 변경되었습니다."); }, onError: error => toast.error(error.message) });
  const createSource = trpc.assessment.admin.createOfficialSource.useMutation({ onSuccess: async () => { await utils.assessment.admin.officialSources.invalidate(); toast.success("공식 출처를 등록했습니다. 다음 확인부터 변경 후보를 감지합니다."); setSourceForm(initialSource); }, onError: error => toast.error(error.message) });
  const syncSources = trpc.assessment.admin.syncOfficialSources.useMutation({ onSuccess: async result => { await Promise.all([utils.assessment.admin.officialSources.invalidate(), utils.assessment.admin.officialChanges.invalidate()]); const candidates = result.results.filter(item => item.status === "candidate_created").length; toast.success(candidates ? `${candidates}개 변경 후보를 검토함에 추가했습니다.` : "공식 출처 확인을 마쳤습니다."); }, onError: error => toast.error(error.message) });
  const reviewChange = trpc.assessment.admin.reviewOfficialChange.useMutation({ onSuccess: async () => { await utils.assessment.admin.officialChanges.invalidate(); toast.success("변경 후보 검토 결과를 저장했습니다."); }, onError: error => toast.error(error.message) });
  if (user?.role !== "admin") return <div className="mx-auto grid min-h-[55vh] max-w-2xl place-items-center text-center"><div><ShieldCheck className="mx-auto h-9 w-9 text-slate-300" /><h1 className="mt-4 text-xl font-bold text-[#183248]">관리자 권한이 필요합니다.</h1><p className="mt-2 text-sm text-slate-500">사용자 역할과 공식 출처 관리는 관리자에게만 허용됩니다.</p></div></div>;
  const submitSource = (event: FormEvent) => { event.preventDefault(); createSource.mutate(sourceForm); };
  return <div className="mx-auto max-w-6xl"><div><p className="text-sm font-semibold text-[#15856B]">WORKSPACE & SOURCE GOVERNANCE</p><h1 className="mt-1 text-3xl font-bold text-[#183248]">관리자 설정</h1><p className="mt-2 text-slate-500">개발용 관리형 AI 사용량과 공식 교육과정·교육청 출처의 변경 후보를 관리합니다.</p></div>
    <ManagedAiUsagePanel usage={managedUsage} isLoading={managedUsageLoading} />
    <section className="mt-7 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Building2 className="h-4 w-4 text-[#15856B]" /><h2 className="font-bold text-[#183248]">공식 출처 추가</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">교육청의 교육과정·평가 지침 목록 페이지처럼 공개적으로 확인 가능한 출처를 등록합니다. 등록된 페이지는 변경 후보만 만들며 자동 게시하지 않습니다.</p><form onSubmit={submitSource} className="mt-5 space-y-3"><div><Label>제공 기관</Label><Input required value={sourceForm.provider} onChange={e => setSourceForm({ ...sourceForm, provider: e.target.value })} className="mt-1" placeholder="예: 서울특별시교육청" /></div><div><Label>출처명</Label><Input required value={sourceForm.title} onChange={e => setSourceForm({ ...sourceForm, title: e.target.value })} className="mt-1" placeholder="예: 고등학교 학업성적관리 시행지침" /></div><div className="grid grid-cols-2 gap-3"><div><Label>출처 유형</Label><select value={sourceForm.sourceType} onChange={e => setSourceForm({ ...sourceForm, sourceType: e.target.value as typeof sourceForm.sourceType })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="education_office">교육청</option><option value="ministry">교육부</option><option value="curriculum_center">교육과정정보센터</option></select></div><div><Label>초기 사용 범위</Label><select value={sourceForm.allowedUse} onChange={e => setSourceForm({ ...sourceForm, allowedUse: e.target.value as typeof sourceForm.allowedUse })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="link_only">원문 링크만</option><option value="metadata_only">메타데이터만</option></select></div></div><div><Label>목록 또는 안내 페이지 URL</Label><Input required type="url" value={sourceForm.listingUrl} onChange={e => setSourceForm({ ...sourceForm, listingUrl: e.target.value })} className="mt-1" placeholder="https://..." /></div><Button disabled={createSource.isPending} className="h-10 w-full rounded-xl bg-[#173B53] hover:bg-[#102C40]">{createSource.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <><Plus className="mr-2 h-4 w-4" />공식 출처 등록</>}</Button></form></article>
      <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-[#183248]">등록된 공식 출처</h2><p className="mt-1 text-xs text-slate-500">변경 감지는 원문을 자동 게시하지 않고 관리자 검토함에 후보만 추가합니다.</p></div><Button onClick={() => syncSources.mutate()} disabled={syncSources.isPending} variant="outline" className="w-fit border-[#B9DCCF] text-[#15856B]"><RefreshCw className={`mr-2 h-4 w-4 ${syncSources.isPending ? "animate-spin" : ""}`} />지금 확인</Button></div><div className="divide-y divide-slate-100">{sourcesLoading ? <p className="p-5 text-sm text-slate-400">출처를 불러오는 중입니다.</p> : sources?.map(source => <div key={source.id} className="flex gap-3 px-5 py-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#E6F4EE] text-[#15856B]"><Building2 className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[#183248]">{source.title}</p><Badge variant="secondary" className="text-[10px]">{sourceTypeLabels[source.sourceType]}</Badge><Badge className="bg-slate-100 text-[10px] text-slate-600 hover:bg-slate-100">{source.allowedUse === "link_only" ? "원문 링크" : source.allowedUse === "metadata_only" ? "메타데이터" : "RAG 승인"}</Badge></div><p className="mt-1 text-xs text-slate-500">{source.provider} · 최근 확인 {source.lastCheckedAt ? new Date(source.lastCheckedAt).toLocaleString("ko-KR") : "전"}</p><p className="mt-1 text-[11px] text-slate-400">상태: {source.lastCheckStatus || "확인 전"}</p></div><a href={source.listingUrl} target="_blank" rel="noreferrer" className="self-center text-[#2D6496]"><ExternalLink className="h-4 w-4" /></a></div>)}</div></article></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-[#183248]">공식 출처 변경 후보</h2><p className="mt-1 text-xs text-slate-500">공식 페이지 변화가 감지되어도 권리 상태와 원문을 확인하기 전에는 기본 문서에 반영되지 않습니다.</p></div><div className="divide-y divide-slate-100">{changesLoading ? <p className="p-5 text-sm text-slate-400">변경 후보를 불러오는 중입니다.</p> : changes?.length ? changes.map(({ change, source }) => <div key={change.id} className="flex flex-col gap-3 px-5 py-4 md:flex-row md:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[#183248]">{change.title}</p><Badge className={change.status === "pending" ? "bg-[#FFF2D8] text-[#B56716] hover:bg-[#FFF2D8]" : change.status === "approved" ? "bg-[#E6F4EE] text-[#15856B] hover:bg-[#E6F4EE]" : "bg-slate-100 text-slate-600 hover:bg-slate-100"}>{change.status === "pending" ? "검토 대기" : change.status === "approved" ? "승인" : "반려"}</Badge></div><p className="mt-1 text-xs text-slate-500">{source.provider} · {new Date(change.detectedAt).toLocaleString("ko-KR")}</p><p className="mt-1 text-xs leading-5 text-slate-500">{change.reason}</p></div><a href={change.documentUrl} target="_blank" rel="noreferrer" className="text-xs font-semibold text-[#2D6496] hover:underline">출처 확인</a>{change.status === "pending" ? <div className="flex gap-2"><Button size="sm" variant="outline" disabled={reviewChange.isPending} onClick={() => reviewChange.mutate({ id: change.id, status: "rejected", reviewNote: "원문·권리 상태 확인 전 반영하지 않음" })}><X className="mr-1 h-3.5 w-3.5" />반려</Button><Button size="sm" disabled={reviewChange.isPending} className="bg-[#15856B] hover:bg-[#106C58]" onClick={() => reviewChange.mutate({ id: change.id, status: "approved", reviewNote: "원문과 권리 상태를 검토했으며 후속 카탈로그 반영 대상으로 승인" })}><Check className="mr-1 h-3.5 w-3.5" />승인</Button></div> : null}</div>) : <div className="p-8 text-center text-sm text-slate-400">아직 감지된 변경 후보가 없습니다. ‘지금 확인’으로 기준값을 만들 수 있습니다.</div>}</div></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4"><Sparkles className="h-4 w-4 text-[#A66C08]" /><div><h2 className="font-bold text-[#183248]">파일럿 교사 플랜</h2><p className="mt-1 text-xs text-slate-500">결제 연동 전 테스트용 기능 권한입니다. 이름과 플랜만 표시하며 이메일·로그인 기록은 보이지 않습니다.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3 font-semibold">이름</th><th className="px-5 py-3 font-semibold">플랜</th><th className="px-5 py-3 font-semibold">권한</th><th className="px-5 py-3 font-semibold">관리</th></tr></thead><tbody className="divide-y divide-slate-100">{isLoading ? <tr><td colSpan={4} className="px-5 py-10 text-center text-slate-400">파일럿 플랜을 불러오는 중입니다.</td></tr> : users?.map(member => <tr key={member.id}><td className="px-5 py-4 font-medium text-[#183248]">{member.name || "이름 없음"}</td><td className="px-5 py-4"><Badge className={member.membershipPlan === "plus" ? "bg-[#FFF2D8] text-[#A66C08] hover:bg-[#FFF2D8]" : "bg-[#E6F4EE] text-[#15856B] hover:bg-[#E6F4EE]"}>{member.membershipPlan === "plus" ? "교사 플러스" : "교사 기본"}</Badge></td><td className="px-5 py-4 text-xs text-slate-500">{member.membershipPlan === "plus" ? "문제집 출력 사용" : "기본 문서 출력"}</td><td className="px-5 py-4"><Button disabled={setPlan.isPending || member.role === "admin"} variant="outline" size="sm" onClick={() => setPlan.mutate({ userId: member.id, membershipPlan: member.membershipPlan === "plus" ? "basic" : "plus" })}>{setPlan.isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : member.membershipPlan === "plus" ? "기본으로 변경" : "플러스로 변경"}</Button></td></tr>)}</tbody></table></div></section>{ORGANIZATION_MANAGEMENT_ENABLED ? <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4"><UsersRound className="h-4 w-4 text-[#15856B]" /><div><h2 className="font-bold text-[#183248]">워크스페이스 사용자</h2><p className="mt-1 text-xs text-slate-500">역할 관리는 기관 도입 준비가 끝난 뒤에만 사용합니다.</p></div></div><div className="p-5"><Button disabled={setRole.isPending} variant="outline" size="sm">기관 역할 관리 준비 중</Button></div></section> : null}</div>;
}
