import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Download, FileDown, Sparkles } from "lucide-react";
import { toast } from "sonner";

export default function Approved() {
  const { data: questions, isLoading } = trpc.assessment.questions.list.useQuery({ status: "approved" }); const { data: exportData, refetch } = trpc.assessment.questions.exportCsv.useQuery(undefined, { enabled: false });
  const download = async () => { const result = exportData ?? (await refetch()).data; if (!result?.count) return toast.error("내보낼 승인 문항이 없습니다."); const blob = new Blob([`\ufeff${result.csv}`], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "approved-questions.csv"; anchor.click(); URL.revokeObjectURL(url); toast.success(`${result.count}개 승인 문항을 CSV로 내보냈습니다.`); };
  return <div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-[#15856B]">APPROVED ITEM BANK</p><h1 className="mt-1 text-3xl font-bold text-[#183248]">승인 문항</h1><p className="mt-2 text-slate-500">최종 승인된 문항과 생성 모델·프롬프트 버전을 관리합니다.</p></div><Button onClick={download} className="h-11 rounded-xl bg-[#173B53] hover:bg-[#102C40]"><Download className="mr-2 h-4 w-4" />CSV 내보내기</Button></div><section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["문항", "유형·난이도", "정답", "출제 의도", "생성 이력"].map(item => <th key={item} className="px-5 py-4 font-semibold">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{isLoading ? <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-400">승인 문항을 불러오는 중입니다.</td></tr> : questions?.length ? questions.map(item => <tr key={item.id} className="align-top"><td className="max-w-md px-5 py-4"><p className="line-clamp-3 font-medium leading-6 text-[#183248]">{item.questionText}</p><span className="mt-2 inline-block text-xs text-slate-400">문항 #{item.id} · {new Date(item.createdAt).toLocaleDateString("ko-KR")}</span></td><td className="px-5 py-4"><Badge variant="outline">{item.questionType}</Badge><p className="mt-2 text-xs text-slate-500">난이도 {item.difficulty} · {item.points}점</p></td><td className="px-5 py-4 font-semibold text-[#15856B]">{item.answer}</td><td className="max-w-xs px-5 py-4 leading-5 text-slate-600">{item.intent}</td><td className="px-5 py-4 text-xs text-slate-500"><p>{item.model}</p><p className="mt-1">{item.promptVersion}</p></td></tr>) : <tr><td colSpan={5} className="px-5 py-14 text-center"><FileDown className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-medium text-slate-600">승인된 문항이 없습니다.</p><p className="mt-1 text-sm text-slate-400">검수함에서 문항을 승인하면 이 목록에서 관리할 수 있습니다.</p></td></tr>}</tbody></table></div></section></div>;
}
