import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { approvedQuickQuizBankItems } from "@/lib/quickQuizApprovedItems";
import { createQuestionDocx, openQuestionPrintView } from "@/lib/questionExport";
import type { ExportQuestion, ExportVisualSpec, QuestionDocumentKind } from "@/lib/questionExport";
import { trpc } from "@/lib/trpc";
import { CheckSquare, Download, FileDown, FileSpreadsheet, FileText, Printer, Search, ShieldCheck, Square } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type SourceFilter = "all" | "regular" | "quick_quiz";
type ApprovedBankItem = { key: string; source: "regular" | "quick_quiz"; createdAt: Date | string; title: string; context: string; exportQuestion: ExportQuestion };

function downloadBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
function dateLabel(value: Date | string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "날짜 확인 필요" : new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium" }).format(date); }
function csvCell(value: unknown) { return `"${String(value ?? "").replace(/"/g, '""')}"`; }

/** 일반 문항과 개별 승인 쪽지시험을 한 보관함에 모으되, 원래 출처는 항상 명확하게 보여 준다. */
export default function Approved() {
  const { data: questions, isLoading: questionsLoading } = trpc.assessment.questions.list.useQuery({ status: "approved" });
  const quickQuizzes = trpc.assessment.quickQuiz.list.useQuery();
  const { data: plan } = trpc.assessment.plan.me.useQuery();
  const { refetch: loadWorkbookQuestions } = trpc.assessment.questions.workbookExport.useQuery(undefined, { enabled: false });
  const [isExporting, setIsExporting] = useState(false);
  const [isPlanDialogOpen, setIsPlanDialogOpen] = useState(false);
  const [sourceFilter, setSourceFilter] = useState<SourceFilter>("all");
  const [search, setSearch] = useState("");
  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(() => new Set());

  const regularItems = useMemo<ApprovedBankItem[]>(() => (questions || []).map(question => ({ key: `regular-${question.id}`, source: "regular", createdAt: question.createdAt, title: question.questionText, context: `${question.questionType} · 난이도 ${question.difficulty} · ${question.points}점`, exportQuestion: { ...question, visualSpec: question.visualSpec as ExportVisualSpec | null } })), [questions]);
  const quickItems = useMemo<ApprovedBankItem[]>(() => approvedQuickQuizBankItems((quickQuizzes.data || []) as Parameters<typeof approvedQuickQuizBankItems>[0]).map(item => ({ key: item.key, source: "quick_quiz", createdAt: item.createdAt, title: item.exportQuestion.questionText, context: `${item.subject} · ${item.unit} · ${item.topic} · ${item.exportQuestion.questionType}`, exportQuestion: item.exportQuestion })), [quickQuizzes.data]);
  const allItems = useMemo(() => [...regularItems, ...quickItems].sort((left, right) => new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime()), [regularItems, quickItems]);
  const visibleItems = allItems.filter(item => (sourceFilter === "all" || item.source === sourceFilter) && `${item.title} ${item.context}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
  const chosenItems = selectedKeys.size ? allItems.filter(item => selectedKeys.has(item.key)) : visibleItems;
  const exportQuestions = chosenItems.map(item => item.exportQuestion);
  const isLoading = questionsLoading || quickQuizzes.isLoading;
  const allVisibleSelected = visibleItems.length > 0 && visibleItems.every(item => selectedKeys.has(item.key));

  const requireQuestions = () => { if (exportQuestions.length) return true; toast.error("내보낼 승인 문항이 없습니다."); return false; };
  const toggleItem = (key: string) => setSelectedKeys(current => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; });
  const toggleVisible = () => setSelectedKeys(current => { const next = new Set(current); visibleItems.forEach(item => allVisibleSelected ? next.delete(item.key) : next.add(item.key)); return next; });
  const clearSelection = () => setSelectedKeys(new Set());

  const downloadCsv = () => {
    if (!requireQuestions()) return;
    const csv = [["출처", "문항", "유형", "난이도", "정답", "해설", "출제 의도"], ...chosenItems.map(item => [item.source === "quick_quiz" ? "쪽지시험" : "일반 문항", item.exportQuestion.questionText, item.exportQuestion.questionType, item.exportQuestion.difficulty, item.exportQuestion.answer, item.exportQuestion.explanation, item.exportQuestion.intent])].map(row => row.map(csvCell).join(",")).join("\n");
    downloadBlob(new Blob([`\ufeff${csv}`], { type: "text/csv;charset=utf-8" }), "승인-문항-보관함.csv");
    toast.success(`${chosenItems.length}개 승인 문항을 CSV로 내보냈습니다.`);
  };
  const downloadDocx = async (kind: QuestionDocumentKind) => { if (!requireQuestions()) return; setIsExporting(true); try { downloadBlob(await createQuestionDocx(exportQuestions, kind), kind === "question-paper" ? "승인-문항-시험지.docx" : "승인-문항-정답-해설지.docx"); toast.success(kind === "question-paper" ? "시험지 DOCX를 만들었습니다." : "정답·해설 DOCX를 만들었습니다."); } catch { toast.error("문서 파일을 만들지 못했습니다. 다시 시도해 주세요."); } finally { setIsExporting(false); } };
  const printPdf = (kind: QuestionDocumentKind) => { if (!requireQuestions()) return; if (!openQuestionPrintView(exportQuestions, kind)) return toast.error("인쇄 창을 열지 못했습니다. 브라우저 팝업 차단 설정을 확인해 주세요."); toast.message("인쇄 창에서 프린터 또는 ‘PDF로 저장’을 선택해 주세요."); };
  const printWorkbook = async () => { if (!plan?.canUseWorkbookExport) return setIsPlanDialogOpen(true); setIsExporting(true); try { const result = (await loadWorkbookQuestions()).data as ExportQuestion[] | undefined; if (!result?.length) return toast.error("일반 승인 문항이 없습니다."); if (!openQuestionPrintView(result.map(question => ({ ...question, visualSpec: question.visualSpec as ExportVisualSpec | null })), "question-paper", { title: "교사 문제집", subtitle: "일반 승인 문항 · 출력 전 범위와 정답을 다시 확인해 주세요.", includeStudentFields: true })) return toast.error("문제집 인쇄 창을 열지 못했습니다. 브라우저 팝업 차단 설정을 확인해 주세요."); toast.success("일반 문항 문제집 인쇄 창을 열었습니다."); } catch (error: any) { if (error?.data?.code === "FORBIDDEN" || error?.message?.includes("교사 플러스")) setIsPlanDialogOpen(true); else toast.error(error?.message || "문제집 출력 권한을 확인하지 못했습니다."); } finally { setIsExporting(false); } };

  return <div className="mx-auto max-w-6xl">
    <DialogPlaceholder open={isPlanDialogOpen} onOpenChange={setIsPlanDialogOpen} />
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-[#15856B]">APPROVED ITEM BANK</p><h1 className="mt-1 text-3xl font-bold text-[#183248]">승인 문항 보관함</h1><p className="mt-2 text-slate-500">일반 문항과 쪽지시험의 <strong>개별 승인 문항</strong>을 함께 찾아 선택·출력합니다.</p></div><AlertDialog><AlertDialogTrigger asChild><Button className="h-11 rounded-xl bg-[#173B53] hover:bg-[#102C40]"><Download className="mr-2 h-4 w-4" />선택 문항 내보내기{selectedKeys.size ? ` (${chosenItems.length})` : ""}</Button></AlertDialogTrigger><AlertDialogContent className="max-w-lg"><AlertDialogHeader><AlertDialogTitle>승인 문항 내보내기</AlertDialogTitle><AlertDialogDescription className="leading-6">선택한 문항이 있으면 선택 문항만, 선택하지 않으면 현재 목록의 문항을 내보냅니다. 시험 보안 지침에 맞는 저장 위치와 출력 장치를 사용해 주세요.</AlertDialogDescription></AlertDialogHeader><div className="rounded-lg border border-[#B9DCCF] bg-[#F2FBF6] p-3 text-sm text-slate-700"><div className="flex gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#15856B]" /><p><strong>{exportQuestions.length}문항 준비됨.</strong> 시험지에는 문항·보기만, 정답·해설지에는 교사용 정답과 해설을 포함합니다.</p></div></div><div className="grid gap-2 sm:grid-cols-2"><AlertDialogAction asChild><Button variant="outline" disabled={isExporting} onClick={() => downloadDocx("question-paper")}><FileText className="mr-2 h-4 w-4 text-[#2D6496]" />시험지 DOCX</Button></AlertDialogAction><AlertDialogAction asChild><Button variant="outline" disabled={isExporting} onClick={() => downloadDocx("answer-sheet")}><FileText className="mr-2 h-4 w-4 text-[#15856B]" />정답·해설 DOCX</Button></AlertDialogAction><AlertDialogAction asChild><Button variant="outline" onClick={() => printPdf("question-paper")}><Printer className="mr-2 h-4 w-4 text-[#B56716]" />시험지 PDF</Button></AlertDialogAction><AlertDialogAction asChild><Button variant="outline" onClick={() => printPdf("answer-sheet")}><Printer className="mr-2 h-4 w-4 text-[#7B56B3]" />정답·해설 PDF</Button></AlertDialogAction><AlertDialogAction asChild><Button variant="outline" onClick={downloadCsv} className="sm:col-span-2"><FileSpreadsheet className="mr-2 h-4 w-4 text-[#15856B]" />CSV 목록</Button></AlertDialogAction></div><div className="border-t border-slate-100 pt-3"><Button disabled={isExporting} onClick={printWorkbook} className="w-full bg-[#9A6711] hover:bg-[#7D510A]"><Printer className="mr-2 h-4 w-4" />일반 문항 문제집 PDF</Button><p className="mt-2 text-xs text-slate-500">문제집 조판은 현재 일반 문항만 지원합니다. 쪽지시험은 위의 선택 문항 출력으로 준비할 수 있습니다.</p></div><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2"><FilterButton active={sourceFilter === "all"} onClick={() => setSourceFilter("all")} label={`전체 ${allItems.length}`} /><FilterButton active={sourceFilter === "regular"} onClick={() => setSourceFilter("regular")} label={`일반 문항 ${regularItems.length}`} /><FilterButton active={sourceFilter === "quick_quiz"} onClick={() => setSourceFilter("quick_quiz")} label={`쪽지시험 ${quickItems.length}`} /></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="문항·단원·개념 검색" className="pl-9" /></div></div>{visibleItems.length ? <div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-3 text-sm"><button type="button" onClick={toggleVisible} className="inline-flex items-center gap-2 font-medium text-[#183248] hover:text-[#15856B]">{allVisibleSelected ? <CheckSquare className="h-4 w-4 text-[#15856B]" /> : <Square className="h-4 w-4" />}{allVisibleSelected ? "현재 목록 선택 해제" : "현재 목록 전체 선택"}</button>{selectedKeys.size ? <button type="button" onClick={clearSelection} className="text-xs text-slate-500 underline underline-offset-2">선택 초기화 ({selectedKeys.size})</button> : <span className="text-xs text-slate-500">필요한 문항만 선택하면 선택 항목만 내보냅니다.</span>}</div> : null}</section>
    <section className="mt-4 grid gap-3 md:grid-cols-2">{isLoading ? <div className="col-span-full rounded-2xl border border-slate-200 bg-white p-10 text-center text-slate-400">승인 문항을 불러오는 중입니다.</div> : visibleItems.length ? visibleItems.map(item => <article key={item.key} className={`rounded-2xl border bg-white p-5 shadow-sm transition-colors ${selectedKeys.has(item.key) ? "border-[#65B99B] ring-1 ring-[#B9DCCF]" : "border-slate-200"}`}><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><Badge className={item.source === "quick_quiz" ? "bg-[#FFF2D8] text-[#B56716] hover:bg-[#FFF2D8]" : "bg-[#E6F4EE] text-[#15856B] hover:bg-[#E6F4EE]"}>{item.source === "quick_quiz" ? "쪽지시험" : "일반 문항"}</Badge><Badge variant="outline">{item.exportQuestion.questionType}</Badge></div><label className="flex cursor-pointer items-center gap-1.5 text-xs text-slate-500"><input type="checkbox" checked={selectedKeys.has(item.key)} onChange={() => toggleItem(item.key)} />선택</label></div><p className="mt-4 line-clamp-3 font-semibold leading-6 text-[#183248]">{item.title}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{item.context}</p><div className="mt-4 flex items-center justify-between gap-3 border-t border-slate-100 pt-3"><span className="text-xs text-slate-400">승인 문항 · {dateLabel(item.createdAt)}</span>{item.source === "quick_quiz" ? <Link href="/quick-quiz" className="text-xs font-medium text-[#B56716] hover:underline">쪽지시험 검수 열기</Link> : <Link href="/review" className="text-xs font-medium text-[#15856B] hover:underline">검수함 열기</Link>}</div></article>) : <div className="col-span-full rounded-2xl border border-dashed border-[#B9DCCF] bg-[#F7FCF9] p-12 text-center"><FileDown className="mx-auto h-8 w-8 text-[#15856B]" /><p className="mt-3 font-medium text-[#183248]">표시할 승인 문항이 없습니다.</p><p className="mt-1 text-sm text-slate-500">일반 문항 또는 쪽지시험에서 문항을 승인하면 이 보관함에서 함께 관리할 수 있습니다.</p></div>}</section>
  </div>;
}

function FilterButton({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) { return <Button type="button" size="sm" variant={active ? "default" : "outline"} onClick={onClick} className={active ? "bg-[#173B53] hover:bg-[#102C40]" : "bg-white"}>{label}</Button>; }
function DialogPlaceholder({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) { return <AlertDialog open={open} onOpenChange={onOpenChange}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>교사 플러스 문제집 출력</AlertDialogTitle><AlertDialogDescription>현재 파일럿 단계에서는 일반 승인 문항 문제집 출력 권한을 확인 중입니다. 결제는 연결하지 않았습니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogAction onClick={() => onOpenChange(false)}>확인</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
