import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { readFileAsDataUrl } from "@/lib/file";
import { trpc } from "@/lib/trpc";
import { FileImage, FileText, Loader2, Plus, Upload } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";
import { toast } from "sonner";

const typeLabels: Record<string, string> = { curriculum: "교육과정", textbook: "교과서", guideline: "출제 지침", teaching: "교수 자료", other: "기타" };
const initial = { title: "", subject: "화학 I", unit: "", applicableYear: "2022", materialType: "curriculum" as const, sourceText: "" };

export default function Materials() {
  const utils = trpc.useUtils();
  const { data: materials, isLoading } = trpc.assessment.materials.list.useQuery();
  const upload = trpc.assessment.materials.upload.useMutation({ onSuccess: async value => { await utils.assessment.materials.list.invalidate(); toast.success(value.ocrStatus === "completed" ? "자료 등록 및 OCR 추출이 완료되었습니다." : "자료가 등록되었습니다."); setForm(initial); setFile(null); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState(initial); const [file, setFile] = useState<File | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!file) return toast.error("PDF 또는 이미지 파일을 선택해 주세요."); if (file.size > 9_500_000) return toast.error("현재 파일은 9MB 이하로 등록해 주세요."); upload.mutate({ ...form, fileName: file.name, mimeType: file.type, base64: await readFileAsDataUrl(file) }); };
  const onFile = (event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] || null);
  return <div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-[#15856B]">RAG KNOWLEDGE BASE</p><h1 className="mt-1 text-3xl font-bold text-[#183248]">참고 자료</h1><p className="mt-2 text-slate-500">교육과정, 교과서, 출제 지침을 등록하면 OCR 텍스트가 검색 근거로 연결됩니다.</p></div><Badge variant="outline" className="h-8 w-fit rounded-lg border-[#B9DCCF] text-[#15856B]">PDF·JPG·PNG 지원</Badge></div>
    <section className="mt-7 grid gap-6 xl:grid-cols-[390px_1fr]"><form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#E6F4EE] text-[#15856B]"><Upload className="h-4 w-4" /></span><h2 className="font-bold text-[#183248]">자료 등록</h2></div><div className="mt-5 space-y-4"><div><Label>자료명</Label><Input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="예: 2022 개정 화학 I 교육과정" className="mt-1.5" /></div><div className="grid grid-cols-2 gap-3"><div><Label>과목</Label><Input required value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} className="mt-1.5" /></div><div><Label>단원</Label><Input required value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })} placeholder="공통 가능" className="mt-1.5" /></div></div><div className="grid grid-cols-2 gap-3"><div><Label>적용 연도</Label><Input required value={form.applicableYear} onChange={e => setForm({ ...form, applicableYear: e.target.value })} className="mt-1.5" /></div><div><Label>자료 유형</Label><select value={form.materialType} onChange={e => setForm({ ...form, materialType: e.target.value as typeof form.materialType })} className="mt-1.5 h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div><div><Label>파일</Label><label className="mt-1.5 flex cursor-pointer flex-col items-center rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-5 text-center hover:border-[#15856B]"><input type="file" accept="application/pdf,image/*" className="sr-only" onChange={onFile} /><FileImage className="h-5 w-5 text-slate-400" /><span className="mt-2 text-sm font-medium text-slate-600">{file ? file.name : "PDF 또는 이미지 선택"}</span><span className="mt-1 text-xs text-slate-400">등록 후 OCR로 텍스트를 추출합니다.</span></label></div><div><Label>보조 텍스트 <span className="font-normal text-slate-400">(선택)</span></Label><Textarea value={form.sourceText} onChange={e => setForm({ ...form, sourceText: e.target.value })} className="mt-1.5 min-h-20" placeholder="OCR 보정 또는 검색에 포함할 텍스트" /></div><Button disabled={upload.isPending} className="h-11 w-full rounded-xl bg-[#173B53] hover:bg-[#102C40]">{upload.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />OCR 및 저장 중</> : <><Plus className="mr-2 h-4 w-4" />자료 등록</>}</Button></div></form>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-[#183248]">등록된 자료 <span className="ml-1 text-sm font-normal text-slate-400">{materials?.length ?? 0}건</span></h2></div><div className="divide-y divide-slate-100">{isLoading ? <p className="p-6 text-sm text-slate-400">자료를 불러오는 중입니다.</p> : materials?.length ? materials.map(material => <div key={material.id} className="flex gap-4 px-5 py-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-[#2D6496]"><FileText className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[#183248]">{material.title}</p><Badge variant="secondary" className="text-[10px]">{typeLabels[material.materialType]}</Badge><Badge className={`text-[10px] ${material.ocrStatus === "completed" ? "bg-[#E6F4EE] text-[#15856B] hover:bg-[#E6F4EE]" : material.ocrStatus === "failed" ? "bg-red-50 text-red-600 hover:bg-red-50" : "bg-slate-100 text-slate-500 hover:bg-slate-100"}`}>OCR {material.ocrStatus === "completed" ? "완료" : material.ocrStatus === "failed" ? "실패" : "대기"}</Badge></div><p className="mt-1 text-sm text-slate-500">{material.subject} · {material.unit} · {material.applicableYear} · {material.fileName}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-400">{material.ocrText || material.sourceText || "추출된 텍스트가 없습니다."}</p></div><a href={material.fileUrl} target="_blank" rel="noreferrer" className="self-center text-xs font-semibold text-[#2D6496] hover:underline">원본 보기</a></div>) : <div className="p-10 text-center"><FileText className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-medium text-slate-600">등록된 참고 자료가 없습니다.</p><p className="mt-1 text-sm text-slate-400">왼쪽에서 교육과정 또는 출제 지침 파일을 등록해 주세요.</p></div>}</div></div></section></div>;
}
