import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { QuestionVisual } from "@/components/QuestionVisual";
import { trpc } from "@/lib/trpc";
import { Check, ChevronRight, CircleAlert, ExternalLink, FileText, History, Pencil, ShieldCheck, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type DraftFields = { questionText: string; choices: string; answer: string; explanation: string; intent: string };
const blank: DraftFields = { questionText: "", choices: "", answer: "", explanation: "", intent: "" };
const statusLabel: Record<string, string> = { approved: "승인", revised: "수정", rejected: "반려" };

// '문제지 p.4', '4쪽', 'page 4'처럼 교사가 입력한 위치에서 PDF 페이지 번호를 찾아 링크에 붙입니다.
function pageFromLocation(value?: string | null) {
  const match = value?.match(/(?:p(?:age)?\.?\s*|쪽\s*|페이지\s*|^\s*)(\d+)/i) || value?.match(/(\d+)\s*(?:쪽|페이지|page|p\.?)/i);
  return match ? Number(match[1]) : null;
}

function sourceLink(source: Record<string, any>, snapshot: Record<string, any>, location: string) {
  const url = snapshot.sourceFileUrl || snapshot.fileUrl || source.sourceFileUrl || source.reference?.sourceFileUrl || source.material?.fileUrl;
  if (!url) return null;
  const isPdf = (snapshot.mimeType || source.sourceMimeType || "").includes("pdf") || /\.pdf(?:$|[?#])/i.test(url);
  const page = isPdf ? pageFromLocation(location) : null;
  return { url: page ? `${url}#page=${page}` : url, page, isPdf };
}

function ProviderHistory({ request, model }: { request?: { providerType: "managed" | "ollama" | "openai_compatible" | "gemini"; providerModel: string; externalTransferConsentAt: Date | null }; model: string }) {
  const providerLabel = request?.providerType === "managed" ? "관리형 AI" : request?.providerType === "ollama" ? "로컬 Ollama" : request?.providerType === "gemini" ? "개인 Gemini API" : request?.providerType === "openai_compatible" ? "개인 OpenAI 호환 API" : "기록 없음";
  return <article className="rounded-2xl border border-[#B9DCCF] bg-[#F7FCF9] p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-[#183248]"><History className="h-4 w-4 text-[#15856B]" />AI 실행 이력</h2><dl className="mt-3 space-y-2 text-xs leading-5 text-slate-600"><div><dt className="inline font-semibold text-[#183248]">제공자 </dt><dd className="inline">{providerLabel}</dd></div><div><dt className="inline font-semibold text-[#183248]">모델 </dt><dd className="inline">{request?.providerModel || model}</dd></div><div><dt className="inline font-semibold text-[#183248]">외부 전송 </dt><dd className="inline">{request?.externalTransferConsentAt ? `요청별 동의 기록됨 · ${new Date(request.externalTransferConsentAt).toLocaleString("ko-KR")}` : "없음"}</dd></div></dl></article>;
}

function EvidenceList({ evidence }: { evidence: any[] }) {
  if (!evidence.length) return <p className="text-xs text-slate-400">연결된 근거가 없습니다.</p>;
  return <div className="space-y-3">{evidence.map((item, index) => {
    const snapshot = (item.sourceSnapshot || {}) as Record<string, any>;
    const isReference = item.sourceType === "reference_question";
    const title = isReference ? `${snapshot.source || item.reference?.source || "기출문제"} · ${snapshot.year || item.reference?.year || "연도 미입력"}` : snapshot.title || item.material?.title || "삭제된 참고 자료";
    const sourceName = isReference ? snapshot.questionNumber || item.reference?.questionNumber || "문항 번호 미입력" : snapshot.fileName || item.material?.fileName || "원본 파일명 보존됨";
    const location = snapshot.sourceLocation || (isReference ? item.reference?.sourceLocation : item.material?.sourceLocation) || "등록 당시 위치 정보 없음";
    const purpose = isReference ? snapshot.intent || item.reference?.intent || item.excerpt || "유형·난이도·출제 의도 참고" : item.sourceType === "guideline" ? "출제 지침 근거" : "교육자료 근거";
    const original = sourceLink(item, snapshot, location);
    return <article key={item.id ?? `${item.sourceType}-${item.sourceId}-${index}`} className={`rounded-xl border p-3 ${isReference ? "border-[#B9DCCF] bg-[#F2FBF6]" : "border-slate-200 bg-slate-50"}`}><div className="flex items-start justify-between gap-2"><p className="text-xs font-semibold text-[#183248]">{title}</p><Badge variant="outline" className="shrink-0 text-[10px]">{isReference ? "기출 유형" : item.sourceType === "guideline" ? "출제 지침" : "참고 자료"}</Badge></div><dl className="mt-2 space-y-1 text-[11px] leading-4 text-slate-600"><div><dt className="inline font-semibold text-slate-700">원본 </dt><dd className="inline">{sourceName}</dd></div><div><dt className="inline font-semibold text-slate-700">위치 </dt><dd className="inline">{location}</dd></div><div><dt className="inline font-semibold text-slate-700">활용 </dt><dd className="inline">{purpose}</dd></div></dl>{original ? <a href={original.url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[11px] font-semibold text-[#116B58] hover:underline"><ExternalLink className="h-3.5 w-3.5" />원본 열기{original.page ? ` · ${original.page}페이지로 이동` : ""}</a> : <p className="mt-3 text-[11px] text-slate-400">연결된 원본 파일이 없어 파일 열기는 사용할 수 없습니다.</p>}{item.excerpt ? <><blockquote className="mt-3 border-l-2 border-[#7EBEAE] pl-2 text-[11px] leading-5 text-slate-500">{item.excerpt}</blockquote><p className="mt-2 text-[10px] leading-4 text-slate-400">수식·첨자·특수문자가 추출 과정에서 달라질 수 있습니다. 최종 검수 전 원본 파일과 대조해 주세요.</p></> : null}</article>;
  })}</div>;
}

export default function Review() {
  const utils = trpc.useUtils();
  const { data: pending, isLoading } = trpc.assessment.questions.list.useQuery({ status: "pending_review" });
  const { data: held } = trpc.assessment.questions.list.useQuery({ status: "validation_hold" });
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const detail = trpc.assessment.questions.detail.useQuery({ id: selectedId || 0 }, { enabled: Boolean(selectedId) });
  const [fields, setFields] = useState<DraftFields>(blank);
  const [reason, setReason] = useState("");

  useEffect(() => { if (detail.data?.question) { const question = detail.data.question; setFields({ questionText: question.questionText, choices: (question.choices || []).join("\n"), answer: question.answer, explanation: question.explanation, intent: question.intent }); setReason(""); } }, [detail.data]);
  useEffect(() => { if (!selectedId && pending?.[0]) setSelectedId(pending[0].id); }, [pending, selectedId]);
  const review = trpc.assessment.questions.review.useMutation({ onSuccess: async () => { await Promise.all([utils.assessment.questions.list.invalidate(), utils.assessment.questions.detail.invalidate()]); toast.success("검수 결과가 기록되었습니다."); setSelectedId(null); }, onError: error => toast.error(error.message) });
  const submit = (action: "approved" | "revised" | "rejected") => { if (!selectedId || reason.trim().length < 2) return toast.error("검수 사유를 2자 이상 기록해 주세요."); review.mutate({ id: selectedId, action, reason, ...(action === "revised" ? { ...fields, choices: fields.choices.split("\n").map(item => item.trim()).filter(Boolean) } : {}) }); };
  const items = [...(pending || []), ...(held || [])];
  const report = detail.data?.question.validationReport as any;

  return <div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-[#15856B]">REVIEW WORKSPACE</p><h1 className="mt-1 text-3xl font-bold text-[#183248]">검수함</h1><p className="mt-2 text-slate-500">생성된 문항과 실제 사용한 근거 자료·발췌·원본 위치를 함께 확인하고 승인·수정·반려합니다.</p></div><Badge className="w-fit bg-[#FFF2D8] text-[#B56716] hover:bg-[#FFF2D8]">검수 대기 {pending?.length ?? 0}건 · 검증 보류 {held?.length ?? 0}건</Badge></div>
    <section className="mt-7 grid gap-5 xl:grid-cols-[310px_minmax(0,1fr)_360px]"><aside className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-4 py-4 font-bold text-[#183248]">문항 목록</div><div className="max-h-[680px] overflow-y-auto">{isLoading ? <p className="p-5 text-sm text-slate-400">불러오는 중입니다.</p> : items.length ? items.map(item => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full border-b border-slate-100 px-4 py-4 text-left transition hover:bg-slate-50 ${selectedId === item.id ? "border-l-4 border-l-[#15856B] bg-[#F2FBF6]" : ""}`}><div className="flex items-center justify-between gap-2"><Badge className={item.status === "validation_hold" ? "bg-red-50 text-red-600 hover:bg-red-50" : "bg-[#E6F4EE] text-[#15856B] hover:bg-[#E6F4EE]"}>{item.status === "validation_hold" ? "검증 보류" : "검수 대기"}</Badge><span className="text-xs text-slate-400">{item.points}점</span></div><p className="mt-2 line-clamp-2 text-sm font-medium leading-5 text-[#183248]">{item.questionText}</p><p className="mt-2 text-xs text-slate-400">{item.questionType} · 난이도 {item.difficulty}</p></button>) : <div className="p-8 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 text-sm font-medium text-slate-600">검수할 문항이 없습니다.</p></div>}</div></aside>
      <main className="min-w-0 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{detail.isLoading ? <p className="text-sm text-slate-400">문항을 불러오는 중입니다.</p> : detail.data ? <><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-5"><div><div className="flex gap-2"><Badge variant="outline">{detail.data.question.questionType}</Badge><Badge variant="outline">난이도 {detail.data.question.difficulty}</Badge><Badge variant="outline">{detail.data.question.points}점</Badge></div><p className="mt-3 text-xs text-slate-400">모델 {detail.data.question.model} · {detail.data.question.promptVersion}</p></div><span className="text-xs text-slate-400">문항 #{detail.data.question.id}</span></div><div className="mt-6 space-y-5">{detail.data.question.visualSpec ? <div><Label>자료</Label><div className="mt-1.5"><QuestionVisual spec={detail.data.question.visualSpec as any} /></div></div> : null}<div><Label>문제</Label><Textarea value={fields.questionText} onChange={e => setFields({ ...fields, questionText: e.target.value })} className="mt-1.5 min-h-32 text-base leading-7" /></div><div><Label>보기 <span className="text-xs font-normal text-slate-400">(한 줄에 하나씩)</span></Label><Textarea value={fields.choices} onChange={e => setFields({ ...fields, choices: e.target.value })} className="mt-1.5 min-h-28" /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>정답</Label><Input value={fields.answer} onChange={e => setFields({ ...fields, answer: e.target.value })} className="mt-1.5" /></div><div><Label>출제 의도</Label><Input value={fields.intent} onChange={e => setFields({ ...fields, intent: e.target.value })} className="mt-1.5" /></div></div><div><Label>해설</Label><Textarea value={fields.explanation} onChange={e => setFields({ ...fields, explanation: e.target.value })} className="mt-1.5 min-h-28" /></div><div><Label>검수 사유</Label><Textarea value={reason} onChange={e => setReason(e.target.value)} className="mt-1.5 min-h-20" placeholder="승인·수정·반려 사유를 기록합니다." /></div><div className="flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-5"><Button onClick={() => submit("rejected")} disabled={review.isPending} variant="outline" className="border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700"><X className="mr-1.5 h-4 w-4" />반려</Button><Button onClick={() => submit("revised")} disabled={review.isPending} variant="outline"><Pencil className="mr-1.5 h-4 w-4" />수정 승인</Button><Button onClick={() => submit("approved")} disabled={review.isPending} className="bg-[#15856B] hover:bg-[#106C58]"><Check className="mr-1.5 h-4 w-4" />승인</Button></div></div></> : <div className="grid min-h-[480px] place-items-center text-center"><div><ChevronRight className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 text-sm text-slate-400">왼쪽에서 검수할 문항을 선택해 주세요.</p></div></div>}</main>
      <aside className="space-y-4">{detail.data ? <><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-[#183248]"><ShieldCheck className="h-4 w-4 text-[#15856B]" />자동 검증 결과</h2><div className="mt-4 space-y-3 text-sm">{[["교육과정 범위", report?.inScope], ["정답·해설 일치", report?.answerExplanationConsistent], ["난이도 적합", report?.difficultyAppropriate], ["출제 지침 준수", report?.guidanceCompliant], ["기출 비복제", !report?.tooSimilar]].map(([label, passed]) => <div key={String(label)} className="flex items-center justify-between"><span className="text-slate-600">{label}</span><span className={passed ? "text-[#15856B]" : "text-red-600"}>{passed ? "통과" : "확인 필요"}</span></div>)}<div className="flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-slate-600">유사도 참고값</span><span className={(report?.similarityScore || 0) < 0.84 ? "text-[#15856B]" : "text-red-600"}>{Math.round((report?.similarityScore || 0) * 100)}%</span></div></div>{report?.notes?.length ? <div className="mt-4 rounded-xl bg-[#FFF9EC] p-3 text-xs leading-5 text-[#8A5A19]">{report.notes.join(" ")}</div> : null}</article><ProviderHistory request={detail.data.generationRequest} model={detail.data.question.model} /><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-[#183248]"><FileText className="h-4 w-4 text-[#2D6496]" />근거 자료 상세</h2><p className="mt-2 text-[11px] leading-4 text-slate-500">생성 시 실제 선택된 발췌와 원본 식별 정보를 보존합니다.</p><div className="mt-4"><EvidenceList evidence={detail.data.sourceEvidence || detail.data.sources} /></div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold text-[#183248]"><History className="h-4 w-4 text-[#7B56B3]" />검수 이력</h2><div className="mt-4 space-y-3">{detail.data.events.length ? detail.data.events.map(event => <div key={event.id} className="border-l-2 border-[#D9C9F0] pl-3"><p className="text-xs font-semibold text-[#183248]">{statusLabel[event.action]}</p><p className="mt-1 text-[11px] leading-4 text-slate-500">{event.reason || "사유 없음"}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(event.createdAt).toLocaleString("ko-KR")}</p></div>) : <p className="text-xs text-slate-400">아직 기록된 검수 이력이 없습니다.</p>}</div></article></> : <article className="rounded-2xl border border-[#F3D6A3] bg-[#FFF9EC] p-5"><CircleAlert className="h-5 w-5 text-[#B56716]" /><p className="mt-3 text-sm leading-6 text-slate-600">근거와 검증 결과는 문항을 선택하면 표시됩니다.</p></article>}</aside></section>
  </div>;
}
