import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Loader2, Plus, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type ScheduleForm = { id?: number; title: string; scheduleDate: string; scheduleTime: string; eventType: "exam" | "deadline" | "meeting" | "review" | "other"; note: string; status: "planned" | "completed" };
const localDate = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const emptySchedule = (): ScheduleForm => ({ title: "", scheduleDate: localDate(), scheduleTime: "", eventType: "exam", note: "", status: "planned" });
const labels = { exam: "시험일", deadline: "마감", meeting: "회의", review: "검수", other: "기타" } as const;

/** 교사 개인의 시험일·마감 계획을 달력과 목록으로 관리한다. 일정은 AI 요청·외부 캘린더와 자동 연결하지 않는다. */
export default function Schedule() {
  const utils = trpc.useUtils();
  const schedules = trpc.assessment.schedules.list.useQuery();
  const [form, setForm] = useState<ScheduleForm>(emptySchedule);
  const [month, setMonth] = useState(() => localDate().slice(0, 7));
  const refresh = () => { void utils.assessment.schedules.list.invalidate(); void utils.assessment.dashboard.invalidate(); };
  const create = trpc.assessment.schedules.create.useMutation({ onSuccess: () => { toast.success("일정을 저장했습니다."); setForm(emptySchedule()); refresh(); }, onError: error => toast.error(error.message) });
  const update = trpc.assessment.schedules.update.useMutation({ onSuccess: () => { toast.success("일정을 수정했습니다."); setForm(emptySchedule()); refresh(); }, onError: error => toast.error(error.message) });
  const remove = trpc.assessment.schedules.remove.useMutation({ onSuccess: () => { toast.success("일정을 삭제했습니다."); if (form.id) setForm(emptySchedule()); refresh(); }, onError: error => toast.error(error.message) });
  const monthDate = useMemo(() => new Date(`${month}-01T12:00:00`), [month]);
  const days = useMemo(() => { const first = new Date(monthDate.getFullYear(), monthDate.getMonth(), 1); const padding = first.getDay(); const count = new Date(monthDate.getFullYear(), monthDate.getMonth() + 1, 0).getDate(); return Array.from({ length: padding + count }, (_, index) => index < padding ? null : index - padding + 1); }, [monthDate]);
  const shown = schedules.data?.filter(item => item.scheduleDate.startsWith(month)) || [];
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.title.trim()) return toast.error("일정 제목을 입력해 주세요."); const payload = { ...form, title: form.title.trim(), scheduleTime: form.scheduleTime || null, note: form.note.trim() || null }; if (form.id) update.mutate({ ...payload, id: form.id }); else create.mutate(payload); };
  const moveMonth = (offset: number) => { const next = new Date(monthDate.getFullYear(), monthDate.getMonth() + offset, 1); setMonth(`${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, "0")}`); };
  const select = (item: NonNullable<typeof schedules.data>[number]) => setForm({ id: item.id, title: item.title, scheduleDate: item.scheduleDate, scheduleTime: item.scheduleTime || "", eventType: item.eventType, note: item.note || "", status: item.status });
  const pending = create.isPending || update.isPending;

  return <div className="mx-auto max-w-6xl"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-[#15856B]">교사 일정</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#183248]">시험일·업무 달력</h1><p className="mt-2 text-slate-500">시험일, 문항 검수 마감, 회의 일정을 한곳에서 정리합니다. 이 일정은 외부 캘린더·AI 요청에 자동으로 전송되지 않습니다.</p></div><Button variant="outline" onClick={() => setForm(emptySchedule())} className="w-fit border-[#9CCFC0] text-[#116B58]"><Plus className="mr-2 h-4 w-4" />새 일정</Button></div>
    <section className="mt-7 grid gap-5 xl:grid-cols-[360px_1fr]"><form onSubmit={submit} className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-[#183248]">{form.id ? "일정 수정" : "새 일정"}</h2><div className="mt-5 space-y-4"><div><Label htmlFor="schedule-title">제목</Label><Input id="schedule-title" maxLength={160} value={form.title} onChange={event => setForm(value => ({ ...value, title: event.target.value }))} placeholder="예: 2학년 화학 I 중간고사" className="mt-1.5" /></div><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="schedule-date">날짜</Label><Input id="schedule-date" type="date" value={form.scheduleDate} onChange={event => setForm(value => ({ ...value, scheduleDate: event.target.value }))} className="mt-1.5" /></div><div><Label htmlFor="schedule-time">시간 (선택)</Label><Input id="schedule-time" type="time" value={form.scheduleTime} onChange={event => setForm(value => ({ ...value, scheduleTime: event.target.value }))} className="mt-1.5" /></div></div><div><Label htmlFor="schedule-type">일정 종류</Label><select id="schedule-type" value={form.eventType} onChange={event => setForm(value => ({ ...value, eventType: event.target.value as ScheduleForm["eventType"] }))} className="mt-1.5 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="exam">시험일</option><option value="deadline">마감</option><option value="meeting">회의</option><option value="review">검수</option><option value="other">기타</option></select></div><div><Label htmlFor="schedule-note">메모 (선택)</Label><Textarea id="schedule-note" maxLength={2000} value={form.note} onChange={event => setForm(value => ({ ...value, note: event.target.value }))} placeholder="준비할 자료나 확인할 사항을 간단히 적어 두세요." className="mt-1.5 min-h-28 resize-y" /></div>{form.id ? <label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={form.status === "completed"} onChange={event => setForm(value => ({ ...value, status: event.target.checked ? "completed" : "planned" }))} />완료한 일정</label> : null}</div><div className="mt-5 flex gap-2"><Button type="submit" disabled={pending} className="flex-1 bg-[#15856B] hover:bg-[#106C58]">{pending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}{form.id ? "수정 저장" : "일정 저장"}</Button>{form.id ? <Button type="button" variant="outline" onClick={() => setForm(emptySchedule())}>취소</Button> : null}</div></form>
      <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><Button size="icon" variant="ghost" aria-label="이전 달" onClick={() => moveMonth(-1)}><ChevronLeft className="h-4 w-4" /></Button><h2 className="font-bold text-[#183248]">{monthDate.toLocaleDateString("ko-KR", { year: "numeric", month: "long" })}</h2><Button size="icon" variant="ghost" aria-label="다음 달" onClick={() => moveMonth(1)}><ChevronRight className="h-4 w-4" /></Button></div><div className="mt-4 grid grid-cols-7 gap-1 text-center text-xs font-semibold text-slate-400">{"일월화수목금토".split("").map(day => <span key={day} className="py-2">{day}</span>)}</div><div className="grid grid-cols-7 gap-1">{days.map((day, index) => { const date = day ? `${month}-${String(day).padStart(2, "0")}` : ""; const entries = shown.filter(item => item.scheduleDate === date); const today = date === localDate(); return <div key={`${date}-${index}`} className={`min-h-20 rounded-xl border p-1.5 text-left ${day ? "border-slate-100 bg-slate-50/60" : "border-transparent"} ${today ? "ring-2 ring-[#B7E4C7]" : ""}`}>{day ? <p className="px-1 text-xs font-semibold text-slate-500">{day}</p> : null}<div className="mt-1 space-y-1">{entries.slice(0, 2).map(item => <button key={item.id} type="button" onClick={() => select(item)} className={`block w-full truncate rounded px-1.5 py-1 text-left text-[10px] font-medium ${item.status === "completed" ? "bg-slate-200 text-slate-500 line-through" : item.eventType === "exam" ? "bg-[#DDF3E9] text-[#106C58]" : "bg-[#E6F0F6] text-[#23516D]"}`}>{item.title}</button>)}</div></div>; })}</div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-[#15856B]" /><h2 className="font-bold text-[#183248]">{monthDate.toLocaleDateString("ko-KR", { month: "long" })} 일정</h2></div>{schedules.isLoading ? <p className="mt-4 text-sm text-slate-500"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />일정을 불러오는 중입니다.</p> : shown.length ? <div className="mt-4 divide-y divide-slate-100">{shown.map(item => <article key={item.id} className="flex gap-3 py-3"><button type="button" aria-label={`${item.title} ${item.status === "completed" ? "미완료로 변경" : "완료 처리"}`} onClick={() => update.mutate({ id: item.id, title: item.title, scheduleDate: item.scheduleDate, scheduleTime: item.scheduleTime || null, eventType: item.eventType, note: item.note || null, status: item.status === "completed" ? "planned" : "completed" })} className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full border ${item.status === "completed" ? "border-[#15856B] bg-[#15856B] text-white" : "border-slate-300 text-transparent"}`}><Check className="h-4 w-4" /></button><button type="button" onClick={() => select(item)} className="min-w-0 flex-1 text-left"><p className={`font-semibold ${item.status === "completed" ? "text-slate-400 line-through" : "text-[#183248]"}`}>{item.title}</p><p className="mt-1 flex items-center gap-2 text-xs text-slate-500"><span className="rounded bg-slate-100 px-1.5 py-0.5">{labels[item.eventType]}</span>{item.scheduleDate}{item.scheduleTime ? <><Clock3 className="h-3 w-3" />{item.scheduleTime}</> : null}</p>{item.note ? <p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{item.note}</p> : null}</button><Button aria-label={`${item.title} 삭제`} size="icon" variant="ghost" className="h-8 w-8 text-slate-400 hover:text-red-600" onClick={() => { if (window.confirm("이 일정을 삭제할까요?")) remove.mutate({ id: item.id }); }}><Trash2 className="h-4 w-4" /></Button></article>)}</div> : <div className="mt-4 rounded-xl border border-dashed border-[#B9DCCF] bg-[#F7FCF9] p-6 text-center"><CalendarDays className="mx-auto h-6 w-6 text-[#15856B]" /><p className="mt-2 text-sm font-semibold text-[#183248]">이번 달 일정이 없습니다.</p><p className="mt-1 text-xs leading-5 text-slate-500">시험일이나 문항 검수 마감을 먼저 등록해 보세요.</p></div>}</section></div></section></div>;
}
