const api = window.teacherLocal;
const pageTitle = document.querySelector("#page-title");
const pageContent = document.querySelector("#page-content");
const statusStrip = document.querySelector("#status-strip");
let currentPage = "home";
let localStatus;
let officialScope = { subject: "화학 I", unit: "공통" };

const escapeHtml = value => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#39;");
const flash = message => { statusStrip.textContent = message; };
const button = (label, id, extra = "") => `<button class="${extra || "primary"}" id="${id}">${label}</button>`;

async function refreshStatus() {
  try { localStatus = await api.getStatus(); const runtimes = localStatus.runtimes; const ollama = runtimes.ollama.running ? `Ollama 실행 중 · ${runtimes.ollama.models.length}개 모델` : "Ollama가 아직 실행되지 않았습니다."; statusStrip.textContent = `로컬 전용 모드 · ${ollama}`; } catch (error) { statusStrip.textContent = `로컬 상태를 확인하지 못했습니다: ${error.message}`; }
}

function setPage(page) { currentPage = page; document.querySelectorAll(".nav").forEach(item => item.classList.toggle("active", item.dataset.page === page)); render(); }
document.querySelectorAll(".nav").forEach(item => item.addEventListener("click", () => setPage(item.dataset.page)));
document.querySelector("#refresh-status").addEventListener("click", refreshStatus);

async function renderHome() { const [materials, references, questions] = await Promise.all([api.listMaterials(), api.listReferences({}), api.listQuestions()]); return `<div class="grid cards"><article class="card"><strong>${materials.length}</strong><span>등록 참고 자료</span></article><article class="card"><strong>${references.length}</strong><span>구조화된 기출문제</span></article><article class="card"><strong>${questions.filter(item => item.status === "pending_review").length}</strong><span>검수 대기 문항</span></article><article class="card"><strong>${questions.filter(item => item.status === "approved").length}</strong><span>승인된 문항</span></article></div><div class="grid two" style="margin-top:18px"><article class="panel"><h2>로컬 사용 원칙</h2><p class="notice">현재 로컬 모드는 Ollama·llama.cpp 모델만 사용합니다. 자료·문항·프롬프트는 외부 개인 API로 자동 전송되지 않습니다.</p></article><article class="panel"><h2>권장 작업 흐름</h2><p class="notice">1. 자료 등록 → 2. 기출문제 → 3. 문항 생성 → 4. 검수·승인 → 5. DOCX·PDF·CSV 내보내기</p></article></div>`; }

async function renderMaterials() { const materials = await api.listMaterials(); return `<div class="grid two"><article class="panel"><h2>참고 자료 등록</h2><div class="field"><label>자료명</label><input id="material-title" placeholder="예: 화학 결합 수업 자료" /></div><div class="field"><label>과목 / 단원</label><div class="row"><input id="material-subject" value="화학 I" /><input id="material-unit" value="공통" /></div></div><div class="field"><label>자료 텍스트 또는 교사 메모</label><textarea id="material-content" placeholder="로컬 생성에 사용할 핵심 내용을 적거나 붙여넣으세요."></textarea></div>${button("로컬 자료 저장", "save-material")}</article><article class="panel"><h2>등록한 자료</h2>${materials.length ? materials.map(item => `<div class="item"><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.subject)} · ${escapeHtml(item.unit)}</p><div class="row" style="margin-top:8px"><button class="small-button delete-material" data-id="${item.id}">삭제</button></div></div>`).join("") : `<p class="empty">등록한 자료가 없습니다.</p>`}</article></div>`; }

async function renderReferences() { const references = await api.listReferences({}); return `<div class="grid two"><article class="panel"><h2>기출문제 등록</h2><div class="field"><label>출처</label><input id="ref-source" placeholder="예: 2025년 6월 모의평가" /></div><div class="field"><label>과목 / 단원 / 문항 번호</label><div class="row"><input id="ref-subject" value="화학 I" /><input id="ref-unit" value="공통" /><input id="ref-number" placeholder="문항 번호" /></div></div><div class="field"><label>문항 또는 유형 메모</label><textarea id="ref-question" placeholder="문항 내용이나 참고할 유형을 적으세요."></textarea></div><div class="field"><label>출제 의도</label><input id="ref-intent" placeholder="예: 결합 종류 비교" /></div>${button("기출문제 저장", "save-reference")}</article><article class="panel"><h2>등록한 기출문제</h2>${references.length ? references.map(item => `<div class="item"><h3>${escapeHtml(item.source)} ${escapeHtml(item.question_number || "")}</h3><p>${escapeHtml(item.question_text)}</p></div>`).join("") : `<p class="empty">등록한 기출문제가 없습니다.</p>`}</article></div>`; }

async function renderOfficialDocuments() { const documents = await api.listOfficialDocuments(officialScope); const selected = documents.filter(item => item.use_for_generation).length; return `<div class="grid two"><article class="panel"><h2>공식 자료 선택</h2><p class="notice">공식 원문을 이 앱에 복제하지 않습니다. 교사가 링크를 열어 원문을 대조하고, 사용할 자료만 문항 생성에 포함합니다.</p><div class="field"><label>과목 / 단원</label><div class="row"><input id="official-subject" value="${escapeHtml(officialScope.subject)}" /><input id="official-unit" value="${escapeHtml(officialScope.unit)}" /><button class="small-button" id="load-official-documents">불러오기</button></div></div><div class="notice warning">현재 선택: ${selected}개 · 선택 정보는 이 PC의 SQLite 저장소에만 기록됩니다.</div></article><article class="panel"><h2>공식 문서 목록</h2>${documents.length ? documents.map(item => `<div class="item"><div class="row" style="justify-content:space-between"><h3>${escapeHtml(item.title)}</h3><button class="small-button official-choice" data-key="${escapeHtml(item.catalog_key)}" data-selected="${item.use_for_generation ? "true" : "false"}">${item.use_for_generation ? "생성에 사용 중" : "생성에 사용"}</button></div><p>${escapeHtml(item.summary)}</p><p class="notice">${escapeHtml(item.issue_number)} · ${escapeHtml(item.applicable_year)} · 링크 전용</p><a href="${escapeHtml(item.official_url)}" target="_blank" rel="noreferrer" class="notice">공식 원문 열기</a></div>`).join("") : `<p class="empty">해당 범위의 공식 자료가 없습니다.</p>`}</article></div>`; }

async function renderGenerate() { const models = localStatus?.runtimes?.ollama?.models || []; const recommendation = localStatus?.recommendation; const officialDocuments = await api.listOfficialDocuments({ subject: "화학 I", unit: "공통" }); const selectedOfficial = officialDocuments.filter(item => item.use_for_generation).length; const recommendAction = !models.length && recommendation?.model ? `<div class="notice warning"><strong>${escapeHtml(recommendation.tier)} 권장: ${escapeHtml(recommendation.model)}</strong><br />${escapeHtml(recommendation.reason)}<br /><button class="small-button" id="pull-recommended-model" data-model="${escapeHtml(recommendation.model)}" style="margin-top:8px">${escapeHtml(recommendation.model)} 준비하기</button></div>` : ""; return `<div class="grid two"><article class="panel"><h2>문항 생성</h2><div class="field"><label>과목 / 단원</label><div class="row"><input id="gen-subject" value="화학 I" /><input id="gen-unit" value="공통" /></div></div><div class="field"><label>로컬 모델</label><select id="gen-model">${models.length ? models.map(model => `<option>${escapeHtml(model)}</option>`).join("") : `<option value="">실행 중인 Ollama 모델 없음</option>`}</select></div><div class="field"><label>문항 요청</label><textarea id="gen-request" placeholder="예: 화학 결합 단원 3점 자료 분석형 1문항을 만들어 주세요."></textarea></div><div class="row"><div class="field" style="flex:1"><label>난이도</label><select id="gen-difficulty"><option>중</option><option>상</option><option>하</option></select></div><div class="field" style="flex:1"><label>배점</label><input id="gen-points" type="number" value="3" /></div></div>${button("로컬 모델로 문항 생성", "generate-question")}</article><article class="panel"><h2>생성 전 확인</h2><p class="notice">로컬 모델만 사용합니다. 자료·기출 텍스트는 이 PC의 SQLite 저장소와 loopback 모델에만 전달됩니다.</p><p class="notice ${selectedOfficial ? "" : "warning"}">화학 I 기준 선택한 공식 자료: ${selectedOfficial}개 · 생성 전 ‘공식 자료’에서 사용 여부를 확인하세요.</p>${models.length ? "" : `<p class="notice warning">Ollama를 설치하고 권장 모델을 준비한 뒤 다시 확인하세요.</p>${recommendAction}`}<div id="generation-result"></div></article></div>`; }

async function renderReview() { const questions = await api.listQuestions(); const pending = questions.filter(item => item.status !== "approved" && item.status !== "rejected"); return `<article class="panel"><h2>검수함</h2>${pending.length ? pending.map(item => `<div class="item"><h3>문항 · ${escapeHtml(item.questionType)} · ${item.points}점</h3><p>${escapeHtml(item.questionText).slice(0, 600)}</p><div class="row" style="margin-top:10px"><button class="small-button review-action" data-id="${item.id}" data-status="approved">승인</button><button class="small-button review-action" data-id="${item.id}" data-status="revised">수정 필요</button><button class="small-button review-action" data-id="${item.id}" data-status="rejected">반려</button></div></div>`).join("") : `<p class="empty">검수할 문항이 없습니다.</p>`}</article>`; }

async function renderApproved() { const approved = await api.listQuestions("approved"); return `<article class="panel"><h2>승인 문항</h2><p class="notice">시험지와 정답·해설은 반드시 별도 파일로 출력됩니다. 보안 저장 위치를 직접 확인해 주세요.</p><div class="row" style="margin:14px 0">${button("시험지 DOCX", "export-docx-question", "outline")}${button("정답·해설 DOCX", "export-docx-answer", "outline")}${button("시험지 PDF", "print-question", "outline")}${button("정답·해설 PDF", "print-answer", "outline")}${button("CSV 목록", "export-csv", "outline")}</div>${approved.length ? approved.map(item => `<div class="item"><h3>${escapeHtml(item.questionText).slice(0, 120)}</h3><p>${item.points}점 · ${escapeHtml(item.questionType)}</p></div>`).join("") : `<p class="empty">승인된 문항이 없습니다.</p>`}</article>`; }

async function bindActions() {
  document.querySelector("#save-material")?.addEventListener("click", async () => { await api.saveMaterial({ title: document.querySelector("#material-title").value, subject: document.querySelector("#material-subject").value, unit: document.querySelector("#material-unit").value, content: document.querySelector("#material-content").value }); flash("로컬 자료를 저장했습니다."); render(); });
  document.querySelectorAll(".delete-material").forEach(item => item.addEventListener("click", async () => { await api.deleteMaterial(item.dataset.id); flash("자료를 삭제했습니다."); render(); }));
  document.querySelector("#save-reference")?.addEventListener("click", async () => { await api.saveReference({ source: document.querySelector("#ref-source").value, subject: document.querySelector("#ref-subject").value, unit: document.querySelector("#ref-unit").value, questionNumber: document.querySelector("#ref-number").value, questionText: document.querySelector("#ref-question").value, intent: document.querySelector("#ref-intent").value }); flash("기출문제를 저장했습니다."); render(); });
  document.querySelector("#load-official-documents")?.addEventListener("click", () => { officialScope = { subject: document.querySelector("#official-subject").value || "화학 I", unit: document.querySelector("#official-unit").value || "공통" }; render(); });
  document.querySelectorAll(".official-choice").forEach(item => item.addEventListener("click", async () => { await api.setOfficialDocumentSelection({ catalogKey: item.dataset.key, useForGeneration: item.dataset.selected !== "true" }); flash("공식 자료 사용 여부를 저장했습니다."); render(); }));
  document.querySelector("#generate-question")?.addEventListener("click", async () => { const resultBox = document.querySelector("#generation-result"); resultBox.innerHTML = `<p class="notice">로컬 모델이 문항을 생성하고 있습니다.</p>`; try { const result = await api.generateQuestion({ model: document.querySelector("#gen-model").value, subject: document.querySelector("#gen-subject").value, unit: document.querySelector("#gen-unit").value, request: document.querySelector("#gen-request").value, difficulty: document.querySelector("#gen-difficulty").value, points: document.querySelector("#gen-points").value }); resultBox.innerHTML = `<h3>검수 전 생성 결과</h3><div class="generated">${escapeHtml(result.response)}</div>`; flash("생성 결과를 검수함에 저장했습니다."); } catch (error) { resultBox.innerHTML = `<p class="notice warning">${escapeHtml(error.message)}</p>`; } });
  document.querySelector("#pull-recommended-model")?.addEventListener("click", async event => { const model = event.currentTarget.dataset.model; if (!window.confirm(`${model} 모델을 내려받습니다. 저장공간과 모델 라이선스를 확인했나요?`)) return; flash(`${model} 모델을 준비하고 있습니다. 다운로드가 끝날 때까지 기다려 주세요.`); try { await api.pullModel(model); await refreshStatus(); flash(`${model} 모델 준비가 완료되었습니다.`); render(); } catch (error) { flash(`모델을 준비하지 못했습니다: ${error.message}`); } });
  document.querySelectorAll(".review-action").forEach(item => item.addEventListener("click", async () => { await api.reviewQuestion({ questionId: item.dataset.id, status: item.dataset.status, reason: "교사 로컬 검수" }); flash("검수 상태를 기록했습니다."); render(); }));
  const exportAction = kind => async () => { try { const result = await api.exportApproved({ kind }); flash(result.saved ? `파일을 저장했습니다: ${result.path}` : "출력을 취소했습니다."); } catch (error) { flash(error.message); } };
  document.querySelector("#export-docx-question")?.addEventListener("click", exportAction("docx-question")); document.querySelector("#export-docx-answer")?.addEventListener("click", exportAction("docx-answer")); document.querySelector("#export-csv")?.addEventListener("click", exportAction("csv")); document.querySelector("#print-question")?.addEventListener("click", exportAction("print-question")); document.querySelector("#print-answer")?.addEventListener("click", exportAction("print-answer"));
}

async function render() { const titles = { home: "오늘의 출제 업무", materials: "참고 자료", references: "기출문제", official: "공식 자료", generate: "문항 생성", review: "검수함", approved: "승인 문항" }; pageTitle.textContent = titles[currentPage]; const renderer = { home: renderHome, materials: renderMaterials, references: renderReferences, official: renderOfficialDocuments, generate: renderGenerate, review: renderReview, approved: renderApproved }[currentPage]; pageContent.innerHTML = await renderer(); await bindActions(); }

await refreshStatus();
await render();
