// 로컬 앱은 공식 원문을 복제하지 않고, 웹앱과 같은 공식 링크·메타데이터만 SQLite에 캐시합니다.
// 카탈로그 갱신은 웹앱의 관리자 승인본을 기준으로 앱 업데이트에 포함합니다.
export const LOCAL_OFFICIAL_DOCUMENTS = [
  { catalogKey: "2022-curriculum-general", title: "2022 개정 교육과정 · 총론", subject: "공통", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 1", rightsStatus: "link_only", summary: "학교급별 적용 시기와 학교 교육과정 운영의 공통 기준을 확인하는 2022 개정 교육과정 총론입니다." },
  { catalogKey: "2015-chemistry-one-curriculum", title: "2015 개정 교육과정 과학과 교육과정 · 화학 I", subject: "화학 I", unit: "공통", applicableYear: "2026 고등학교 3학년 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=C&s=moe&m=0404&opType=N&boardSeq=60747", issueNumber: "교육부 고시 제2015-74호 · 별책 9", rightsStatus: "link_only", summary: "화학 I 시험 범위 확인을 위한 2015 개정 과학과 교육과정 공식 고시입니다." },
  { catalogKey: "ncic-2022-original-index", title: "NCIC 2022 개정 교육과정 원문 및 해설서", subject: "화학", unit: "공통", applicableYear: "2025~2027 적용", documentType: "achievement_standard", officialUrl: "https://ncic.re.kr/inv/org/list.do?ck=main", issueNumber: "NCIC 원문 인벤토리", rightsStatus: "link_only", summary: "국가교육과정정보센터에서 과목별 원문과 해설서를 탐색할 수 있는 공식 인벤토리입니다." },
  { catalogKey: "2022-middle-science-curriculum", title: "2022 개정 교육과정 · 중등 과학", subject: "중등 과학", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9", rightsStatus: "link_only", summary: "중학교 과학의 성취기준과 내용 체계를 확인하는 2022 개정 과학과 교육과정 공식 문서입니다." },
  { catalogKey: "2022-middle-mathematics-curriculum", title: "2022 개정 교육과정 · 중등 수학", subject: "중등 수학", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 8", rightsStatus: "link_only", summary: "중학교 수학의 성취기준과 내용 체계를 확인하는 2022 개정 수학과 교육과정 공식 문서입니다." },
  { catalogKey: "2022-high-integrated-science-one", title: "2022 개정 교육과정 · 통합과학1", subject: "통합과학1", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9", rightsStatus: "link_only", summary: "고등학교 과학 공통 과목 통합과학1의 내용 체계와 성취기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-integrated-science-two", title: "2022 개정 교육과정 · 통합과학2", subject: "통합과학2", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9", rightsStatus: "link_only", summary: "고등학교 과학 공통 과목 통합과학2의 내용 체계와 성취기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-science-inquiry-one", title: "2022 개정 교육과정 · 과학탐구실험1", subject: "과학탐구실험1", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9", rightsStatus: "link_only", summary: "고등학교 과학 공통 과목 과학탐구실험1의 탐구·실험 성취기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-science-inquiry-two", title: "2022 개정 교육과정 · 과학탐구실험2", subject: "과학탐구실험2", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9", rightsStatus: "link_only", summary: "고등학교 과학 공통 과목 과학탐구실험2의 탐구·실험 성취기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-physics-curriculum", title: "2022 개정 교육과정 · 물리학", subject: "물리학", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9·20", rightsStatus: "link_only", summary: "고등학교 과학 일반 선택 물리학과 과학 계열 선택 과목 기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-chemistry-curriculum", title: "2022 개정 교육과정 · 화학", subject: "화학", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9·20", rightsStatus: "link_only", summary: "고등학교 과학 일반 선택 화학과 과학 계열 선택 과목 기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-life-science-curriculum", title: "2022 개정 교육과정 · 생명과학", subject: "생명과학", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9·20", rightsStatus: "link_only", summary: "고등학교 과학 일반 선택 생명과학과 과학 계열 선택 과목 기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-earth-science-curriculum", title: "2022 개정 교육과정 · 지구과학", subject: "지구과학", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 9·20", rightsStatus: "link_only", summary: "고등학교 과학 일반 선택 지구과학과 과학 계열 선택 과목 기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-common-mathematics-one", title: "2022 개정 교육과정 · 공통수학1", subject: "공통수학1", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 8", rightsStatus: "link_only", summary: "고등학교 수학 공통 과목 공통수학1의 성취기준과 내용 체계를 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-common-mathematics-two", title: "2022 개정 교육과정 · 공통수학2", subject: "공통수학2", unit: "공통", applicableYear: "2025~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 8", rightsStatus: "link_only", summary: "고등학교 수학 공통 과목 공통수학2의 성취기준과 내용 체계를 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-algebra-curriculum", title: "2022 개정 교육과정 · 대수", subject: "대수", unit: "공통", applicableYear: "2026~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 8", rightsStatus: "link_only", summary: "고등학교 수학 일반 선택 과목 대수의 내용 체계와 성취기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-calculus-one-curriculum", title: "2022 개정 교육과정 · 미적분Ⅰ", subject: "미적분Ⅰ", unit: "공통", applicableYear: "2026~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 8", rightsStatus: "link_only", summary: "고등학교 수학 일반 선택 과목 미적분Ⅰ의 내용 체계와 성취기준을 확인하는 공식 문서입니다." },
  { catalogKey: "2022-high-probability-statistics-curriculum", title: "2022 개정 교육과정 · 확률과 통계", subject: "확률과 통계", unit: "공통", applicableYear: "2026~2027 적용", documentType: "curriculum", officialUrl: "https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&lev=0&statusYN=W&s=moe&m=0404&opType=N&boardSeq=93458", issueNumber: "교육부 고시 제2022-33호 · 별책 8", rightsStatus: "link_only", summary: "고등학교 수학 일반 선택 과목 확률과 통계의 내용 체계와 성취기준을 확인하는 공식 문서입니다." },
  { catalogKey: "kice-achievement-standard-search", title: "KICE 성취기준·평가기준 검색", subject: "공통", unit: "성취기준", applicableYear: "현재 제공", documentType: "achievement_standard", officialUrl: "https://stas.moe.go.kr/", issueNumber: "학생평가지원포털", rightsStatus: "link_only", summary: "문항을 성취기준·평가기준에 연결할 때 사용하는 공식 검색·자료 경로입니다." },
  { catalogKey: "kice-assessment-tool-library", title: "KICE 학생평가 도구 자료", subject: "공통", unit: "평가도구", applicableYear: "현재 제공", documentType: "guideline", officialUrl: "https://stas.moe.go.kr/cmn/search/searchList", issueNumber: "학생평가지원포털", rightsStatus: "link_only", summary: "수행평가·서논술형·채점기준 설계에 참고하는 공식 자료 경로입니다." },
  { catalogKey: "edunet-achievement-level-library", title: "에듀넷 성취수준(평가기준) 자료실", subject: "공통", unit: "성취수준", applicableYear: "현재 제공", documentType: "achievement_standard", officialUrl: "https://www.edunet.net/cmnBoard/list/57", issueNumber: "에듀넷 자료실", rightsStatus: "link_only", summary: "2022 개정 교육과정 성취수준과 평가기준을 과목별로 확인하는 공식 자료실입니다." },
];

export function documentsForScope(subject, unit = "공통") {
  return LOCAL_OFFICIAL_DOCUMENTS.filter(document => (document.subject === subject || document.subject === "공통") && (document.unit === unit || document.unit === "공통"));
}
